#!/bin/bash -l
#SBATCH -p serial
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 1
#SBATCH -t 72:00:00
#SBATCH -e output
#SBATCH -o output
#SBATCH --open-mode=append

##UNCOMMENT THIS PART IF YOU OBTAIN ERROR OF TYPE:
##/var/spool/slurmd/job4726218/slurm_script: line 11: cd /wrk/users/ineefjes/DATABASE/SA_CLUSTERS/NEUTRAL/SYS_3SA/ABC/ABC_2_1_0_0; sh runJKCS2_explore.sh;: No such file or directory

#args=`echo $@`
#args="${args%\"}"
#args="${args#\"}"
#eval "$args"

##AND COMMENT THIS GUY:
eval "$@"

