#!/bin/bash
############################################################
## JAKUB KUBECKA 2018                                     ##
## Program that collect your results from JKCS folders    ##
## To understand program run help:                        ##
##       for help use arguement -help                     ##
############################################################
## "It's funny that I can call on girlfrien Lol, she does ##
## not know if I am laughing at her."       Jakub Kubecka ##
############################################################

###############################################################################
############################### DECLARATIONS ##################################
###############################################################################

# locate TOOLS path
scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"
toolspath="$scriptpath/../TOOLS"

# load names
source $toolspath/LOADING/names.txt
# load functions
source $toolspath/LOADING/functions.sh
# load user setup
source ~/.JKCSusersetup.txt

# print inserted command
echoCOMMAND COMMAND: $scriptfile "$@" >> output

###############################################################################
###################################### HELP ###################################
###############################################################################

### THIS IS HELP

function help {
  printf "#################################################################\n"
  printf "$scriptfile HELP:\n"
  printf "Program that collect your results from JKCS folders\n"
  printf """
  $scriptfile ${cfCYAN}[OPTIONS(s)] [FOLDER]${cfDEF}

  ${cfMAGENTA}OPTIONS:${cfDEF}
   -help ............ print this help and exit 
   -oc/-onlycollect . only collects pickle file
   -orca ............ if you collect results from ORCA runs
   OTHERS: -clean,-cleanfull,-forces,-eldisp,-forcedisp
  
  ${cfMAGENTA}OUTPUTS:${cfDEF} 
    -collection[${cfBLUE}FOLDER${cfDEF}].pkl:
      crucial file that contains all data from the folder  
    -collection[${cfBLUE}FOLDER${cfDEF}].txt:
      XYZ_full_path  Radius_Of_Gyration  Electronic_Energy  
    -results[${cfBLUE}FOLDER${cfDEF}].dat:
       =file with removed redundant structures (sorted by enegry)
    -movie[${cfBLUE}FOLDER${cfDEF}].xyz:
       =Molden usable file to visualize the structures

  ${cfMAGENTA}TIPS:${cfDEF}
   define output by yourself: (see JKQC --help)
      JKQC collection[${cfBLUE}FOLDER${cfDEF}].pkl -pXYZ -rg -el -dip -pol
      JKQC collection[${cfBLUE}FOLDER${cfDEF}].pkl -ePKL -rg -el -g -lf 
 
  ${cfMAGENTA}EXAMPLES:${cfDEF}
    $scriptfile ABC                         
    $scriptfile XTB -oc                     
    $scriptfile DFT_HIGH -loc               
"""
   # FOR REMOVING WRONG BONDING: (number of C-C, C-O, and O-H bonds)
   # JKCS4_collect -pXYZ -rg -el -dip -script JKgaussstat \"-b2 C C 1.6\" -script JKgaussstat \"-b2 C O 1.6\" -script JKgaussstat \"-b2 O H 1.1\" \n"""

  printf "#################################################################\n"
  exit
}

###############################################################################
################################  USER INPUT  #################################
################################ DO NOT TOUCH #################################
################################################################################

arguments=("$@")       # arguments of this script
arguments_help=()      # 
arguments_help_pass=() # arguments which are passed if all arguments are passed

# check what everything wants user to print
JKloadprint

# load colours
JKloadcolours           # some coloured output

# check -help option
JKloadhelp             # check if user asks for -help

# program 
program=XTB
method=none #THERE WAS A PROBLEM THAT PEOPLE WERE USING FROM NAME FOR FOLDERS AND THEN IT COLLECTED XTB
#JKloadprogram

# check for folderbasename_something arguments and in case enter directories
JKloaddirs
currentdir=${PWD##*/}
currentdirpath=$PWD

# load amount of molecules
if [ -e $inputfile ]
then
  M=`head -n 1 $inputfile | awk '{print $6}'`
else
  JKecho 1 "No ${cfYELLOW}${inputfile}${cfDEF} file. (${cfRED}Assuming M=1 if needed!!!${cfDEF})"
  M=1;
fi

# -loc or load supercomputer parameters
JKloadsupercomputer

###############################################################################
################################  USER INPUT  #################################
################################ DO NOT TOUCH #################################
###############################################################################
#reading arguments important for this script
#basically search just for the FOLDER.
Qjpt=1 #jobs per task
Qpickle=1 #Do I want to pickle afterwards?
Qclean=0 #Do I want to clean after pickling?
Qrecollect=1
Qonlycollect=0 #after JKQC no recollecting will be done
Qarray=1 #submit jobs as array?
Qarraymax=0 #max jobs per array
Qforces=0 #collect forces?
Qdisp_electronic_energy=0
Qdisp_forces=0

ADDdependency=""

last=""
# loop over all arguments
arguments_help=()
for i in "${!arguments[@]}"
do
  iter="${arguments[$i]}"
  firstletter=`echo $iter | cut -c 1`
  if [ "$firstletter" == "-" ] || [ ! -z "$last" ]
  then
    # Jobs per task !! it is actually tasks per job
    if [ "$iter" == "-tpj" ] || [ "$iter" == "-jpt" ]
    then
      last="-jpt"
      continue
    fi
    if [ "$last" == "-jpt" ];
    then
      last=""
      Qjpt=$iter
      continue
    fi
    # Forces
    if [ "$iter" == "-forces" ] || [ "$iter" == "-force" ]
    then
      Qforces=1
      continue
    fi
    # Electronic energy dispersion correction
    if [ "$iter" == "-eldisp" ]
    then
      Qdisp_electronic_energy=1
      continue
    fi
    # Forces dispersion correction
    if [ "$iter" == "-forcedisp" ]
    then
      Qdisp_forces=1
      continue
    fi
    # Array submission
    if [ "$iter" == "-array" ]
    then
      Qarray=1
      echo "No need to use $iter argument anymore. [Used by default.]"
      continue
    fi
    #Qarraymax
    if [ "$iter" == "-arraymax" ]
    then
      last="-arraymax"
      Qarray=1
      continue
    fi
    if [ "$last" == "-arraymax" ]
    then
      Qarraymax="$iter"
      last=""
      continue
    fi
    # ORCA
    if [ "$iter" == "-orca" ] 
    then
      program="ORCA"
      echo "No need to use $iter argument anymore. [ORCA recognized automatically (if .out is used).]" 
      continue
    fi
    # JKQC
    if [ "$iter" == "-pickle" ] || [ "$iter" == "-JKQC" ] || [ "$iter" == "-JKQCpickle" ]
    then
      #Qpickle=1
      echo "No need to use $iter argument anymore. [Used by default.]"
      continue
    fi
    # JKQCclean
    if [ "$iter" == "-clean" ] || [ "$iter" == "-JKQCclean" ]
    then
      Qpickle=1
      Qclean=1
      continue
    fi
    # JKQCcleanfull
    if [ "$iter" == "-cleanfull" ] || [ "$iter" == "-JKQCcleanfull" ] || [ "$iter" == "-fullclean" ]
    then
      Qpickle=1
      Qclean=2
      continue
    fi
    # JKQCrecollect
    if [ "$iter" == "-JKQCrecollect" ]
    then
      Qrecollect=1
      continue
    fi
    # Qonlycollect
    if [ "$iter" == "-onlycollect" ] || [ "$iter" == "-oc" ]
    then
      Qonlycollect=1
      continue
    fi
    # Dependency
    if [ "$iter" == "-dependency" ]
    then
      last="-dependency"
      continue
    fi
    if [ "$last" == "-dependency" ]
    then
      ADDdependency=" --dependency=afterany:$iter "
      continue
    fi
    arguments_help+=( "${arguments[i]}" )
  else
    if [ -d "$iter" ]
    then
      method="${iter%/*}"
    else
      arguments_help+=( "${arguments[i]}" )
    fi
  fi
done
arguments=("${arguments_help[@]}")


###############################################################################
################################ MAIN PROGRAM #################################
################################ DO NOT TOUCH #################################
###############################################################################

#FILES AND FOLDER NAMES DECLARATION
if [ ! -e "$method" ]
then
  JKecho 0 "Please specify the name of an existing folder properly (even if it is XTB). [${cfRED}EXITING${cfDEF}]"
  exit
fi
JKecho 1 "Collecting data from ${cfBLUE}${method}${cfDEF} folder."
#files
savefile="$collectionfile${method}.txt"
savepklfile="$collectionfile${method}.pkl"
resultfile="$resultsfile${method}.dat"
movie="$moviefile${method}.xyz"
if [ -e $savefile ]; then rm $savefile; fi
touch $savefile
if [ -e $resultfile ]; then rm $resultfile;fi
if [ -e $movie ]; then rm $movie;fi
JKecho 2 "Output files checked (${cfYELLOW}$savefile${cfDEF},${cfYELLOW}$resultfile${cfDEF},${cfYELLOW}$movie${cfDEF})"

#SUBFOLDER DEFINITION
if [ ! -d ${method} ]
then
  JKecho 0 "Folder ${cfBLUE}${method}${cfDEF} does not exist.[${cfRED}EXITING${cfDEF}]"
  exit
fi
if [ -d ${method}/${name}-LM ]
then
  subfolders="${method}/${name}-LM"
elif [ -d ${method}/${name}-LM_v1 ]
then
  subfolders=`ls -d ${method}/${name}-LM_v*/ | xargs`
else
  subfolders=`ls -d ${method}/${method}_*/calc-LM | xargs`
  if [ -z "$subfolders" ]
  then
    subfolders="${method}"
  fi
fi
JKecho 2 "Subfolder(s) storing the data: ${cfBLUE}${subfolders}${cfDEF}"

#DID SUBFOLDER FINISHED CORRECTLY ???
JKecho 2 "Is everything done there?"
###
testdone=`JKcheck $method | awk '{print $5}'`
if [ "$testdone" != "100.00" ] && [ "$testdone" != "" ]
then
  JKecho 0 "The subfolder ${cfBLUE}${method}${cfDEF} still has jobs running."
  JKecho 0 "If you continue to collect, the collected data may be incomplete."
  JKecho 0 "Do you want to continue anyway and collect the data? [yes/no]"
  read answer
  if [ "$answer" == "y" ] || [ "$answer" == "yes" ] || [ "$answer" == "Y" ] || [ "$answer" == "YES" ] || [ "$answer" == "Yes" ]
  then
    JKecho 1 "Ok, I will continue."
    #rm $method/.* 2>/dev/null
    #rm ./.* 2>/dev/null
  else 
    JKecho 0 "Collection will not be performed [${cfRED}EXITING${cfDEF}]"
    exit
  fi
else
  rm $method/.* 2>/dev/null
fi
###

######### CHECKING SOME ARGUMENTS:
# loop over all arguments
Qs=3
Qu="2 3"
arguments_hpass=()
arguments_hcatch=()
for i in "${!arguments[@]}"
do
  iter="${arguments[$i]}"
  if [ "$iter" == "-gibbs" ] || [ "$iter" == "-g" ] || [ "$iter" == "-freq" ] || [ "$iter" == "--freq" ]
  then
    Qs=4
    Qu+=" 3"
    arguments_hcatch+=( "-g" )
    continue 
  fi
  if [ "$iter" == "-gibbsh" ] || [ "$iter" == "-gh" ]
  then
    Qs=4
    Qu+=" 3"
    arguments_hcatch+=( "-g -v 0.996 -fc 100" )
    continue
  fi
  arguments_hpass0+=( "$iter" )
done
arguments=${arguments_hpass0[@]}
for i in "${!arguments[@]}"
do
  iter="${arguments[$i]}"
  if [ "$iter" == "-dip" ]
  then
    Qu+=" 1"
    arguments_hcatch+=( "$iter" )
    continue
  fi
  arguments_hpass+=( "$iter" )
done
#arguments=("${arguments_help[@]}")
hpass=${arguments_hpass[@]}
hcatch=${arguments_hcatch[@]}
if [ -z "$hpass" ]
then
  if [ $Qpickle -eq 1 ]
  then
    arguments=( "-ePKL" )
  else
    arguments=( "-pXYZ" )
  fi
  arguments+=( "-rg" )
  arguments+=( "-el" )
  arguments+=( "${arguments_hcatch[@]}" )
else
  Qs=-1
  Qu=""
fi

### GOING THROUGH ALL SUBBFOLDERS
Qjpt_iter=0
jobscount=0
if [ $Qpickle -eq 0 ]
then
  JKecho 2 "Going through all subfolders: ${cfBLUE}$subfolders${cfDEF}"
else
  #TODO Do I really want to recollect everytime?
  if [[ "$method" == *"ABC"* ]] && [[ "$method" != *"DFT"* ]]
  then
    logsouts=`ls $method/calc-LM/*.xyz $method/*/calc-LM/*.xyz $method/*/*/calc-LM/*.xyz 2>/dev/null | wc -w`
  else
    logs=`find $method -maxdepth 4 -name "*.log" | wc -l`
    outs=`find $method -maxdepth 4 -name "*.out" | wc -l`
    JKecho 3 "    Found $logs log files."
    if [ $logs -gt 0 ]
    then 
      for i in $method/*.log $method/*/*.log $method/*/*/*.log
      do
        if [ ! -e $i ]; then continue; fi
        xyz=`echo $i | rev | cut -c4- | rev`xyz
        if [ ! -e $xyz ]; then JKlog2xyz $i -topath; fi
      done
    else
      program="ORCA"
      JKecho 3 "    Found $outs out files."
      for i in $method/*.out $method/*/*.out $method/*/*/*.out
      do
	if [ ! -e $i ]; then continue; fi
	xyz=`echo $i | rev | cut -c5- | rev`.xyz
	if [ ! -e $xyz ]; then JKout2xyz $i ; fi
      done
    fi
    logsouts=`echo $logs+$outs | bc`
  fi
  if [ $logsouts -eq 0 ]
  then
    JKecho 2 "I cannot recollect if there is anything to collect (xyz/logs/outs)"
    Qrecollect=0
  fi
  JKecho 3 "Qrecollect = $Qrecollect"
  if [ $Qrecollect -eq 1 ] #&& [[ "$method" != *"ABC"* ]]
  then
    rm $method/*.pkl $method/*/*.pkl $method/*/*/*.pkl 2>/dev/null
  fi
  PKLinsubfolders=`ls $method/*.pkl $method/*/*.pkl $method/*/*/*.pkl 2>/dev/null | xargs`
  if [ ! -z "$PKLinsubfolders" ]
  then if [ $Qclean -eq 0 ]
    then
      subfolders=""
      JKecho 2 "No need to enter any subfolder (.pkl files exist) ... straight to collecting."
    else
      JKecho 2 "No need to collect anything from folders (.pkl files exist)."
      JKecho 2 "However, I will remove unnecessary files in all subfolders: ${cfBLUE}$subfolders${cfDEF}"
    fi
  else
    JKecho 2 "Going through all subfolders: ${cfBLUE}$subfolders${cfDEF}"
  fi
fi
for subfolder in $subfolders
do
  Qjpt_iter=`echo $Qjpt_iter + 1 |bc`
  ## ENTERING FOLDER
  JKecho 3 "    Analyzing subfolder ${cfBLUE}$subfolder${cfDEF}."
  cd $subfolder
  #################################################################
  # command ... it looks crazy but it has to be done like this due to ""
  #command="$toolspath/SCRIPTS/JKcollect RUN $savefile  "${arguments[@]}
  #printf "$command" > run${scriptfilecommand}.sh
  #if [ $method == "ABC" ] || [ $method == "ABC-XTB" ] || [ $method == "ABC_XTB" ]
  if [[ "$method" == *"ABC"* ]] && [[ "$method" != *"DFT"* ]]
  then
    if [ -e 0.xyz ]
    then
      rm *.log *.pkl 2>/dev/null
      cd ..
      sh rename.sh
      cd calc-LM
    fi
    test=`ls *.xyz 2>/dev/null | wc -l`
    if [ $test -ne 0 ]
    then
      test2=`ls *.log 2>/dev/null | wc -l`
      if [ $test2 -ne $test ]
      then
        rm *.log 2>/dev/null
        for i in *.xyz
        do
          base=$(basename $i .xyz)
          test=`grep -c "Energy:" $i`
          if [ $test -gt 0 ]
          then
            energy=`grep "Energy:" $i | awk '{print $2}'`
          else
            energy=`head -n 2 $i | tail -n 1`
          fi
          echo "ABC" > ${base}.log
          echo "ABC energy: $energy" >> ${base}.log
        done
      fi
    fi
  fi
  ######
  if [ $Qpickle -eq 0 ]
  then
    echoCOMMAND $toolspath/SCRIPTS/JKcollect RUN $savefile "${arguments[@]}">run${scriptfilecommand}.sh
  else
    if [ -z "$PKLinsubfolders" ]
    then
      if [ $program == "ORCA" ] 
      then
        addarg+=" -orcaext out -collect out"
      fi
      if [ $Qforces == "1" ]
      then
        addarg+=" -forces"
      fi
      if [ $Qdisp_electronic_energy == "1" ]
      then
        addarg+=" -eldisp"
      fi
      if [ $Qdisp_forces == "1" ]
      then
        addarg+=" -forcedisp"
      fi
      echo "source ~/.JKCSusersetup.txt;" > run${scriptfilecommand}.sh
      echo "program_JKQCpickle $addarg -noex -folder ./ -out $savepklfile" >> run${scriptfilecommand}.sh
    else
      echo "source ~/.JKCSusersetup.txt" > run${scriptfilecommand}.sh
    fi
    if [ $Qclean -gt 0 ]
    then
      echo "rm -r ../.run *.inp *.sh *.xyz *.log *.out *.cmd *.com TMP 2>/dev/null" >> run${scriptfilecommand}.sh   
    fi
  fi
  commandTODO="cd $PWD; sh run${scriptfilecommand}.sh;"
  cd $currentdirpath 
  if [ "$Qperform" == 2 ]
  then
    echo $commandTODO >> $method/.crealTODO.txt
    echo $commandTODO >> $method/commands_TODO.txt
  else
    echo $commandTODO >> $method/.Qjpt_commands_TODO.txt
    if [ $Qjpt_iter -eq $Qjpt ]
    then
      cat $method/.Qjpt_commands_TODO.txt | xargs -d$'\n' >> $method/commands_TODO.txt
      rm $method/.Qjpt_commands_TODO.txt
      Qjpt_iter=0
      jobscount=`echo $jobscount+1|bc`
    fi
  fi
  JKecho 3 "    Command ${cfMAGENTA}$commandTODO${cfDEF} [${cfCYAN}$command${cfDEF}] written to ${cfBLUE}$method${cfDEF}/${cfYELLOW}commands_TODO.txt${cfDEF}"
done
if [ -e $method/.Qjpt_commands_TODO.txt ]
then
  cat $method/.Qjpt_commands_TODO.txt | xargs -d$'\n' >> $method/commands_TODO.txt
  rm $method/.Qjpt_commands_TODO.txt
  jobscount=`echo $jobscount+1|bc`
fi
###

### PREPARING SUBMITTING FOR ALL JOBS IN METHOD FOLDER
cd $currentdirpath/$method
if [ "$Qperform" == 2 ]; then jobscount=`echo $subfolders | xargs -n 1 | wc -l`; fi
JKecho 2 "Counting number of jobs: ${cfGREEN}$jobscount${cfDEF}"

if [ "$Qperform" == 2 ]
then
  echo "1 $method/" >> ../.link.txt
fi

### PREPARING SUBMITTING FOR THE CONTROL JOB WHICH COLLECTS ALL SUBCOLLECTIONS
#  savefile=$2
#  #I DO NOT NEED THE GUYS BELOW THEY GO TO UNIQUENESS
#  resultfile=$3                                    ##
#  movie=$4                                         ##
#  Qs=$5                                            ## 
#  #UNIQUENNESS                                     ##
#  args=${@:6}
JKecho 2 " + Sending to CONTROL collection." 
#
if [ $Qpickle -eq 0 ]
then
  #commandTODO="while [ 1 -eq 1 ]; do testdone=\`JKcheck $method -num\` ; if [ \"\$testdone\" == \"100.00\" ]; then $toolspath/SCRIPTS/JKcollect CONTROL $savefile $resultfile $movie $Qs $Qu; break; else sleep 1; fi; done "
  commandTODO="$toolspath/SCRIPTS/JKcollect CONTROL $savefile $resultfile $movie $Qs $Qu; "
else
  #if [ $Qclean -eq 2 ]
  #then
  #  removingcommand="rm -r $method;"
  #else
  #  removingcommand=""
  #fi
  #commandTODO="while [ 1 -eq 1 ]; do testdone=\`JKcheck $method -num\` ; if [ \"\$testdone\" == \"100.00\" ]; then source ~/.JKCSusersetup.txt; PKLinsubfolders=\`ls $method/*.pkl $method/*/*.pkl $method/*/*/*.pkl 2>/dev/null | xargs\`; program_JKQCpickle \$PKLinsubfolders -out $savepklfile >> output; program_JKQCpickle  $savepklfile ${arguments[@]} >  $savefile; "
  commandTODO="source ~/.JKCSusersetup.txt; PKLinsubfolders=\`ls $method/c*.pkl $method/*/c*.pkl $method/*/*/c*.pkl 2>/dev/null | xargs\`; program_JKQCpickle \$PKLinsubfolders -out $savepklfile >> output; program_JKQCpickle  $savepklfile ${arguments[@]} >  $savefile; "
  if [ $Qonlycollect -eq 0 ]
  then
    commandTODO+="$toolspath/SCRIPTS/JKcollect CONTROL $savepklfile $resultfile $movie $Qs $Qu; "
  fi
  #commandTODO+="break; else sleep 1; fi; done"
fi
if [ $Qclean -eq 2 ]
then
  commandTODO+="rm -r $method;"
fi
if [ "$Qperform" == 2 ]
then
  echo $commandTODO >> ../.crealTODO.txt
fi

### Sending jobs ###
JKecho 2 "Counting amount of jobs: ${cfBLUE}$jobscount${cfDEF} (max possible ${cfBLUE}$SCtasks${cfDEF})"
if [ $jobscount -le $SCtasks ]
then
  SCtasks=$jobscount
else
  if [ "$Qperform" != 2 ]  && [ "$METHODsupercomputer" != "loc" ]
  then
    JKecho 0 "Max number of jobs to be sent is greater than allowed.[WARNING]"
    JKecho 0 "Either use [${cfCYAN}-maxtasks${cfDEF} ${cfBLUE}$jobscount${cfDEF}] option or use ${cfCYAN}JKperform2${cfDEF} option.[WARNING]"
    #exit
  fi
  SCtasks=$jobscount
fi
JKecho 2 "Tasks used: ${cfBLUE}$SCtasks${cfDEF}"
if [ "$METHODsupercomputer" == "loc" ]
then
  Qarray=0
fi

##Qlinking=0
##if [ $Qlinking -eq 1 ]
##then
##  echo "LINK 1 $currentdirpath" >> commands_TODO.txt
##  if [ -e ../commands_TODO.txt ]
##  then
##    cp ../commands_TODO.txt ../commands_TODO.txt_help
##    echo "LINK 1 $currentdirpath/$method" > ../commands_TODO.txt
##    cat ../commands_TODO.txt_help >> ../commands_TODO.txt
##    rm ../commands_TODO.txt_help
##  else
##    echo "LINK 1 $currentdirpath/$method" > ../commands_TODO.txt
##  fi
##fi

### THE SUBMITTING ITSELF
if [ $SCtasks -eq 1 ]
then
  Qarray=0
fi
for i in `seq $SCtasks -1 1`
do
  if [ "$Qperform" == 2 ]
  then
    $SC_command sh $toolspath/SCRIPTS/JKperform2.sh
    echo "$SC_command sh $toolspath/SCRIPTS/JKperform2.sh" >> output
  else
    #echo "`tail -n $i commands_TODO.txt | head -n 1`" > .run$i
    if [ $Qarray -eq 1 ]
    then
      if [ $i -eq 1 ]
      then
        if [ $Qarraymax -gt 0 ]
        then
          arraymax="%$Qarraymax"
        else
          arraymax=""
        fi
        SC_command_array=`echo $SC_command | sed "s/sbatch/sbatch --array=1-$SCtasks$arraymax $ADDdependency/"`
        JKecho 2 "$SC_command"
        #TODO
        echo "$SC_command_array 'tail -n \${SLURM_ARRAY_TASK_ID} commands_TODO.txt | head -n 1 | sh'" >> output
        echo "$SC_command_array 'tail -n \${SLURM_ARRAY_TASK_ID} commands_TODO.txt | head -n 1 | sh'" > .runP
        #echo  "$SC_command0 'sh .run\${SLURM_ARRAY_TASK_ID}'" >> output
        #echo  "$SC_command0 'sh .run\${SLURM_ARRAY_TASK_ID}'" > .run
        #echo  "$SC_command0 'sh .run1'" >> output
        #echo  "$SC_command0 'sh .run1'" > .run
        #job=$(eval $SC_command "`tail -n $i commands_TODO.txt | head -n 1`")
        job=$(/bin/bash .runP)
        JKecho 2 "submitted"
        if [ ! -z "$job" ] ;then echo $job;fi
        echo $job | awk '{print $4}'  >> .jobs.txt
      fi
    else
      #TODO
      SC_command_dep=`echo $SC_command | sed "s/sbatch/sbatch $ADDdependency/"`
      echo "$SC_command_dep 'tail -n $i commands_TODO.txt | head -n 1 | sh'" >> output
      echo "$SC_command_dep 'tail -n $i commands_TODO.txt | head -n 1 | sh'" > .runP
      #echo  "$SC_command sh .run$i" >> output
      #echo  "$SC_command sh .run$i" > .run
      #job=$(eval $SC_command "`tail -n $i commands_TODO.txt | head -n 1`")
      job=$(/bin/bash .runP)
      #job=$(eval `cat .run`)
      if [ ! -z "$job" ] ;then echo $job;fi
      echo $job | awk '{print $4}'  >> .jobs.txt
    fi
  fi
done
cd $currentdirpath

JKecho 2 "Sending collector."
if [ "$Qperform" != 2 ]
then
  JKecho 3 "Command ${cfMAGENTA}$commandTODO${cfDEF}"
  echo  "$SC_command '$commandTODO'" >> output
  JKecho 3 "Submitting CONTROL command"
  if [ $SCtasks -eq 0 ]
  then
    SC_command_dep=$SC_command
  else
    job_id=`echo $job | awk '{print $4}'`
    SC_command_dep=`echo $SC_command | sed "s/sbatch/sbatch --dependency=afterany:$job_id/"`
  fi
  echo  "$SC_command_dep '$commandTODO'" > .runC
  job=$(/bin/bash .runC)
  #job=$(eval $SC_command "$commandTODO")
  if [ ! -z "$job" ];then echo $job; fi
  if [ "$METHODsupercomputer" != "loc" ]
  then
    echo $job | awk '{print $4}'  >> .jobs.txt  
  fi
fi
JKecho 1 "Subfolder finished/submitted."









