#!/bin/bash
subfolders="$*"

if [ -e .help ];
then
  rm .help;
fi 

folders=`ls -d SYS_*/ 2>/dev/null`
if [ -z "$folders" ]
then
  folders="./"
  if [ -e "../.help" ] 
  then 
    rm ../.help 
  fi
fi
  
for i in $folders; 
do  
  cd $i
  if [ -z "$subfolders" ]
  then
    subsselected=`ls -d */`
  else
    subsselected=$subfolders
  fi

  for j in $subsselected
  do
    if [ -e $j ]
    then
      cd $j
      if [ -e .crealTODO.txt ] 
      then
        v1=`wc -l .crealTODO.txt | awk '{print $1}'`; 
      else 
        v1=0
      fi
      if [ -e .crealDONE.txt ]
      then
        v2=`wc -l .crealDONE.txt | awk '{print $1}'`;
        if [ -e .link.txt ] 
        then
          v2m=`cat .link.txt | awk 'BEGIN{s=0}{s=s+$1}END{print s}'`
          v2=`echo $v2-$v2m | bc -l`
        fi
      else
        v2=0
      fi
      if [ $v1 -eq 0 ]
      then
        v3="--XXX--"
      else 
        v3="= "`echo $v2/$v1*100 | bc -l | awk '{printf "%.2f\n",$1}'`" %"; 
      fi
      cd ..
    else 
      v1="--XXX--"
      v2="--XXX--"
      v3="--XXX--"
    fi
    echo $i $j $v2/$v1 $v3 >> ../.help;  
  done
  cd ..
done
cat .help | sort -nrk 4 | column -t
rm .help
