#!/bin/bash
Q_num=0;
subfolders=""
for i in $*
do
  if [ "$i" == "-num" ]
  then
    Q_num=1
    continue
  fi
  subfolders+=" $i"
done

helpfile=.help$RANDOM

if [ -e $helpfile ];
then
  rm $helpfile;
fi 

folders=`ls -d SYS_*/ 2>/dev/null`
if [ -z "$folders" ]
then
  folders="./"
  if [ -e "../$helpfile" ] 
  then 
    rm ../$helpfile 
  fi
fi
  
for i in $folders; 
do  
  cd $i
  if [ -z "$subfolders" ]
  then
    subsselected=`ls -d */`
  else
    subsselected=$subfolders
  fi

  for j in $subsselected
  do
    if [ -e $j ]
    then
      cd $j
      if [ -e .crealTODO.txt ] 
      then
        v1=`wc -l .crealTODO.txt | awk '{print $1}'`; 
      elif [ -e .jobs.txt ] 
      then
        v1=`wc -l .jobs.txt | awk '{print $1}'`
      else 
        v1=0
      fi
      if [ -e .crealDONE.txt ]
      then
        v2=`wc -l .crealDONE.txt | awk '{print $1}'`;
        if [ -e .link.txt ] 
        then
          v2m=`cat .link.txt | sed 's/2/1/g' | awk 'BEGIN{s=0}{s=s+$1}END{print s}'`
          v2=`echo $v2-$v2m | bc -l`
        fi
      elif [ -e .jobs.txt ]
      then
        v2=0;
        for job in `seq 1 $v1`
        do
          jobN=`head -n $job .jobs.txt | tail -n 1`
          jobR=`squeue -o "%.18i %.2t" --j $jobN 2>/dev/null | grep "$jobN" | awk '{print $2}'` 
          if [ "$jobR" == "" ] || [ "$jobR" == "C" ] || [ -z "$jobN" ]
          then
            v2=`echo $v2+1| bc`
          fi
        done
      else
        v2=0
      fi
      if [ $v1 -eq 0 ]
      then
        subsubfolders=`ls -d */ 2>/dev/null`
        if [ -z "$subsubfolders" ]
        then
          v3="--XXX--"
        else
          v1=`echo $subsubfolders | xargs -n 1 | wc -l`
          v1=`echo $v1 | bc -l`
          v2=$v1
          v3="= 100.00 %"
        fi
      else 
        v3="= "`echo $v2/$v1*100 | bc -l | awk '{printf "%.2f\n",$1}'`" %"; 
      fi
      cd ..
    else 
      v1="--XXX--"
      v2="--XXX--"
      v3="--XXX--"
    fi
    echo $i $j $v2/$v1 $v3 >> ../$helpfile;  
  done
  cd ..
done
if [ $Q_num -eq 1 ]
then
  cat $helpfile | sort -nrk 4 | column -t | awk '{print $5}'
else
  cat $helpfile | sort -nrk 4 | column -t
fi
rm $helpfile
