#!/bin/bash -norc
scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"
export PATH=$scriptpath:$PATH              #MANIPULATE
export PATH=$scriptpath/../../JKCSx:$PATH  #JKCSx
######
for i in `ls -d SYS*`
do
 cd $i
 echo $i
 eval "$@"
 cd ..
# echo ''
done

