#!/bin/bash
############################################################
## JAKUB KUBECKA 2018                                     ##
## Program for analysis of pulling str from gaussian .log ##
## To understand program run help:                        ##
##        JKlog2xyz -help                                 ##
############################################################
## "If architectures have made same amount of mistakes as ##
## me in calculation. Where would we live?" Jakub Kubecka ##
############################################################

### THIS IS HELP
function help {
  echo "THIS IS HELP:"
  echo "Program for analysis of pulling str from gaussian .log"
  echo """
  JKlog2xyz [OPTIONS] [FILES]
  OPTIONS:
   -help ........ print this help and exit
   -abc ......... print structure in format of ABCluster
   -ma,-matchabc. uses MATCH from ~/.JKCSusersetup.txt to make -abc
   -new \"XX\" .... new name of file [e.q.: test]
   -xtb ......... structure is from XTB output
   -f,-forces ... print forces as well [Hartree/Bohr]
   -units ....... converts Bohrs to Angstroms
   -topath ...... saves files to the original path
  FILES:
   gaussian (G16) output is expected
  EXAMPLES:
     JKlog2xyz
     JKlog2xyz 2.log 3.log
     JKlog2xyz -abc guanidine.log
     JKlog2xyz -topath nitro/guanidine.log
  """
  exit
}
### PREPARING WHAT AND HOW
what=""
Qforce=0
Qunit="1.0"
Qabc=0
Qnewname=""
Qnew=0
QdipXTB=0
Qxtb=0
Qtopath=0
next=0
last=""
for i in $*
do
  if [ "$i" == "-help" ] || [ "$i" == "--help" ]; then help;exit;fi
  firstletter=`echo $i | cut -c 1`
  if [ $firstletter == "-" ] || [ $next -eq 1 ]
  then
    ### CHECK IF ABC INPUT IS REQUIRED
    if [ "$i" == "-abc" ]
    then 
      Qabc=1
    fi
    if [ "$i" == "-matchabc" ] || [ "$i" == "-ma" ]
    then
      Qabc=2
    fi
    ### Qforce 
    if [ "$i" == "-f" ] || [ "$i" == "-forces" ] || [ "$i" == "-force" ]
    then
      Qforce=1
      continue
    fi
    ### -new XX
    if [ "$last" == "-new" ]
    then
      Qnew=1
      Qnewname=$i
      last=""
      next=0
    fi
    if [ "$i" == "-new" ]
    then
      next=1
      last="-new"
    fi
    ###
    if [ "$i" == "-dip" ]
    then
      QdipXTB=1
    fi
    ###
    if [ "$i" == "-xtb" ]
    then
      Qxtb=1
    fi
    ### -topath
    if [ "$i" == "-topath" ]   
    then
      Qtopath=1
    fi
    ### unit
    if [ "$i" == "-units" ]
    then
      Qunit=`echo 1/0.529177 | bc -l`
      continue
    fi
    ###
  else
    what+="$i "
  fi
done
### CHECK WHAT
if [ -z "$what" ]; then what=`ls *.log`;fi

### MAIN PROGRAM // in the case a lot of file might take a few seconds
echo "JKlog2xyz: Wait a moment ..." 

function convertG16 {
    ### Finding information about number of atoms
    test=`grep -c 'NAtoms=' $file`
    if [ $test -eq 0 ]
    then
      #D=`grep "Deg. of freedom" $file | head -n 1 | awk '{print $4}'`
      #if [ $D -eq 0 ]; then N=1;fi
      #if [ $D -eq 1 ]; then N=2;fi
      #if [ $D -eq 3 ]; then N=3;fi
      #if [ $D -gt 3 ]; then N0=`echo $D+6|bc`;N=`echo $N0/3|bc`;fi

      # this is better because of some symmetry shits:
      #N=`grep -C 2 "Distance matrix (angstroms):" $file | head -n 1 | awk '{print $1}'`
      #N=`grep -C 2 "Rotational constants" $file | tail -n 5 | head -n 1 | awk '{print $1}'`
      #N=`grep -C 4 "symmetry adapted cartesian basis functions" $file | tail -n 9 | head -n 1 | awk '{print $1}'`
      N=`grep -C 2 "Rotational constants" 1w.log | head -n 1 | awk '{print $1}'`
    else
      N=`grep 'NAtoms=' $file | head -n 1 | awk '{print $2}'`
    fi
    if [ -z $N ];
    then
       #echo "JKlog2xyz: File $file is not covertable!!! (I will try if it is XTB file ... if yes, use -xtb next time)";
       #$( cd "$(dirname "$0")" ; pwd -P )/JKlog2xyz $file -xtb
       convertXTB
       return;
    fi
    N1=`echo $N+1 |bc`
    N2=`echo $N+2 |bc`

    grep -C $N1 "Symbolic Z-matrix:" $file | tail -n $N | awk '{print $1}' | sed 's/^16/S/g' | sed 's/^1/H/g' | sed 's/^8/O/g' | sed 's/^6/C/g' | sed 's/^7/N/g' > helpingfile1
    grep -C $N2 " Center     Atomic      Atomic             Coordinates (Angstroms)" $file | tail -n $N | awk '{print $4,$5,$6}' > helpingfile2

    if [ $Qforce -eq 1 ]
    then
      grep -C $N2 " Center     Atomic                   Forces (Hartrees/Bohr)" $file | tail -n $N | awk -v unit=$Qunit '{print $3*unit,$4*unit,$5*unit}' > helpingfile3
    fi

    ### CREATING NEW FILE
    if [ $Qnew -eq 1 ]
    then
      newfile=$(basename $Qnewname .xyz).xyz
    else
      newfile=${prepos}$(basename $file .log).xyz
    fi
    if [ $Qtopath -eq 1 ]
    then	
      newfile="$( cd "$(dirname "$file")"; pwd -P )"/$newfile
    fi
    if [ -e $newfile ]; then rm $newfile;fi

    echo " $N" >> $newfile
    # Let us save energy on 2. row
    freqQ=`grep -c "Free Energies" $file`
    if [ "$freqQ" -eq 1 ]
    then
      energy=" Free_Energy: `grep "Free Energies" $file | awk '{print $8}'`"
      energy+=" Electronic_Energy: `grep "SCF Done" $file | tail -n 1 | awk '{print $5}'`"
    else
      if [ $Qforce -ne 1 ]
      then
        energy=" Electronic_Energy: `grep "SCF Done" $file | tail -n 1 | awk '{print $5}'`"
      else
        energy=" `grep "SCF Done" $file | tail -n 1 | awk '{print $5}'`"
      fi
    fi
    if [ $QdipXTB -eq 1 ]
    then
      energy+=" Dipole_moment: `grep "molecular dipole:" $file | tail -n 1 | awk '{print $5}'`"
    fi
    echo "$JKenergy" >> $newfile

    if [ $Qforce -ne 1 ]
    then
      paste helpingfile1 helpingfile2 | column -t >> $newfile
    else
      paste helpingfile1 helpingfile2 helpingfile3 | column -t >> $newfile
    fi
}

function convertXTB {
    output=`echo $file | rev | cut -c4- | rev`xyz
    if [ -e "$output" ]
      then
      #echo "xyz file exists, is gonna be deleted."
      rm $output
    fi
    Natoms=`grep 'number of atoms' $file | awk '{print $5}'`
    if [ -z "$Natoms" ]
    then
      echo "File $file is not convertale."
      return
    fi
    echo "   $Natoms" >> $output
    echo $file >> $output
    Natoms2=`echo $Natoms+2 | bc`
    grep -C $Natoms2 'final structure' $file | tail -n $Natoms | awk '{print $4 "\t " $1*0.529177249 "\t " $2*0.529177249 "\t " $3*0.529177249}'  >> $output
}

for file in $what
do
  if [ $Qxtb -eq 0 ]
  then
    convertG16
    ### ABC input ###
    if [ $Qabc -gt 0 ];
    then 
      # add comment line line 
      echo "all32_cgenff q  epsilon (kJ/mol) sigma (AA)" >> $newfile 
      if [ $Qabc -eq 2 ]
      then
        if [ -e ~/.JKCSusersetup.txt ]
        then 
          source ~/.JKCSusersetup.txt
        else
          echo "Sorr, the following file must exist: ~/.JKCSusersetup.txt [EXITING]"
          exit
        fi
        program_MATCH $file
      fi      
  
      ### START LOOP ###
      # loop over all atoms (you need to know amount of atoms N)
      for i in `seq 1 $N`
      do 
        # (NPA) or (Mulliken) charges? // NPA prefered if they exist
        test=`grep -c "Summary of Natural Population Analysis" $file`
        if [ $test -gt 0 ]
        then
          text="Summary of Natural Population Analysis"
          N1new=`echo $N1+4 |bc`
          elem=1
        else
          test=`grep -c "Mulliken charges and spin densities:" $file`
          if [ $test -gt 0 ]
          then 
            text=" Mulliken charges and spin densities:"
          else
            text=" Mulliken charges:" 
          fi
          N1new=$N1
          elem=2
        fi
        # taking charge
        q=`grep -C $N1new "$text" $file | tail -n $N | awk '{print $3}' | head -n $i | tail -n 1`
        # asking for element
        e=`grep -C $N1new "$text" $file | tail -n $N | awk -v var=$elem '{print $var}' | head -n $i | tail -n 1`
        if [ $Qabc -eq 1 ]
        then
          # giving some valeus (LJ parameters) to the element       !!!! these values are not set up properly !!!!!! 
          text=""
          if [ $e == "C" ] || [ $e == "c" ]; then text=" 0.30     3.6    # C 0.2-0.5 3.5-3.6 ";fi
          if [ $e == "O" ] || [ $e == "o" ]; then text=" 1.05     3.15   # O 0.8-1 3.15";fi
          if [ $e == "S" ] || [ $e == "s" ]; then text=" 1.05     3.55   # S ";fi
          if [ $e == "Cl" ] || [ $e == "cl" ] || [ $e == "CL" ]; then text=" 0.6276     4.0447 # Cl";fi
          if [ $e == "F" ] || [ $e == "f" ]; then text=" 0.56     2.90   # F ";fi
          if [ $e == "N" ] || [ $e == "n" ]; then text=" 0.84     3.30   # N 0.7-0.9 3.1-3.3";fi
          if [ $e == "H" ] || [ $e == "h" ]; then text=" 0.19     0.4    # H 0.1-0.2 0.4-3 | OH 0.16 0.4 | CH 0.12 2.4";fi
          #if missing element then you have to upgrade this code
          if [ -z "$text" ]; then echo "element potential coefficients are missing. Contact Jacob, he can fix it very easily.";fi
        else
          TYPE=`head -n $i .matchHELP2 | tail -n1 | awk '{print $3}'`
          text=`grep "^$TYPE " $PATH_MATCH/MATCH/resources/top_all36_cgenff/par_all36_cgenff.prm | tail -n 1 | awk '{print -4.184*$3 " " $4*2^(5/6)}'`
        fi
        # put it in the end of the strABC.xyz
        echo "$q $text" >> $newfile
      done
      ### END LOOP ###
    fi
    ### END ABC INPUT ###
  else
    convertXTB
  fi
done

if [ -e helpingfile1 ]; then rm helpingfile1; fi
if [ -e helpingfile2 ]; then rm helpingfile2; fi
if [ -e helpingfile3 ]; then rm helpingfile3; fi

echo "JKlog2xyz: Done :-D"
