#!/bin/bash

### THIS IS HELP
function help {
  echo "THIS IS HELP:"
  echo "Program for that change name of file accordingly to its composition"
  echo """
  JKname [file(s).xyz]
  BEHAVIOUR
    - recognize: sa, sam, msa, gd, am, dma, p, co2, hom10, aq
    - if file.xyz exist, then create file-#.xyz, where # is increasing nnumber

  OPTIONS:
    -log ...... use .log instead if .xyz (convert first .log to .xyz)
    OTHERS: -hom, -msa, -buoh

  EXAMPLES:
    JKname 
    JKname -log
    JKname 123.xyz
    JKname -log 123.log 234.log
  """
  exit
}
Qmsa=0
Qhom=0
Qbuoh=0
FILES=""

Qlog=0
next=0
for i in $*
do
  if [ "$i" == "-help" ] || [ "$i" == "--help" ]; then help;exit;fi
  firstletter=`echo $i | cut -c 1`
  if [ $firstletter == "-" ] || [ $next -eq 1 ]
  then
    if [ "$i" == "-hom" ]
    then
      Qhom=1
      continue
    fi
    if [ "$i" == "-msa" ]
    then
      Qmsa=1
      continue
    fi
    if [ "$i" == "-buoh" ]
    then
      Qbuoh=1
      continue
    fi
    if [ "$i" == "-log" ]
    then
      Qlog=1
      continue
    fi
  fi
  files+=" $i"
done

if [ -z "$files" ]
then
  if [ $Qlog -eq 1 ]
  then 
    files=`ls *.log`
  else
    files=`ls *.xyz`
  fi
fi

#echo FILES = $files
for file in $files
do
  if [ $Qlog -eq 1 ]
  then
    #echo FILE = $file
    JKlog2xyz $file >> output 
    fileXYZ=`basename $file .log`.xyz
  else
    fileXYZ=`basename $file .xyz`.xyz
  fi
  
  atoms=`cat $fileXYZ | awk '{print $1}' | xargs`
  
  C=0
  S=0
  O=0
  H=0
  N=0
  Na=0
  Cl=0

  for i in $atoms
  do
    case $i in 
    "Na") Na=`echo $Na + 1 | bc` 
         ;;
    "Cl") Cl=`echo $Cl + 1 | bc` 
         ;;
    "C") C=`echo $C + 1 | bc` 
         ;;
    "S") S=`echo $S + 1 | bc` 
         ;;
    "O") O=`echo $O + 1 | bc` 
         ;;
    "H") H=`echo $H + 1 | bc` 
         ;;
    esac
  done
  
  echo Na${Na}Cl${Cl}C${C}N${N}O${O}S${S}H${H}

  # NaCl seed
  seed=0
  if [ $Na -ge 1 ] && [ $Cl -ge 1 ]
  then
    seed=1
    Na=0
    Cl=0
  fi 
  # BuOH
  buoh=0
  if [ $Qbuoh -ge 1 ] && [ $C -ge 1 ]
  then
    buoh=`echo $C/4 | bc`
    C=0
    O=`echo $O-1*$buoh | bc`
    H=`echo $H-10*$buoh | bc`
  fi
  # HOM
  hom=0
  if [ $Qhom -ge 1 ] && [ $C -ge 10 ]
  then
    if [ $C -ge 20 ]
    then
      hom=2
    else
      hom=1
    fi
    C=`echo $C-10*$hom | bc`
    O=`echo $O-8*$hom | bc`
    H=`echo $H-16*$hom | bc`
  fi
  # MSA ... no MSAm
  msa=0
  if [ $Qmsa -ge 1 ] && [ $C -ge 1 ] && [ $S -ge 1 ]
  then
    msa=`echo $C | bc` 
    C=`echo $C-$msa | bc`
    S=`echo $S-$msa | bc`
    O=`echo $O-3*$msa | bc`
    H=`echo $H-4*$msa | bc`
  fi
  # H2SO4
  sam=0
  sa=$S
  O=`echo $O-4*$sa | bc`
  H=`echo $H-2*$sa | bc`
  S=`echo $S-$sa | bc`

  # CO2 if just C and O are present
  co2=0
  if [ $C -gt 0 ] && [ $O -gt 0 ] && [ $N -eq 0 ] && [ $H -eq 0 ]
  then
    co2=$C
    C=`echo $C-$co2 | bc`
    O=`echo $O-2*$co2 | bc`
  fi  
  
  if (( $(echo "$N > $C" |bc -l) ))
  then
  # GD = C1N3H5
    dma=0
    gd=$C
    H=`echo $H-5*$gd | bc`
    N=`echo $N-3*$gd | bc`
    C=`echo $C-1*$gd | bc`
  else
  # DMA = C2N1H7
    gd=0
    dma=$N
    H=`echo $H-7*$dma | bc`
    N=`echo $N-1*$dma | bc`
    C=`echo $C-2*$dma | bc`
  fi

  # A = NH3
    am=$N
    H=`echo $H-3*$am | bc`
    N=`echo $N-1*$am | bc`
  
  # W = H2O
    aq=$O
    H=`echo $H-2*$aq | bc`
 
  # proton
    p=$H
    if [ $p -eq -1 ]
    then
      sam=1
      sa=`echo $sa-1 | bc`
      H=0
    else
      H=`echo $H-1*$p | bc`
    fi
 
  echo C${C}N${N}O${O}S${S}H${H}
  name=""
  if [ $seed -gt 0 ]; then echo seed = $seed;name+="${seed}seed"; fi
  if [ $buoh -gt 0 ]; then echo buoh = $buoh;name+="${buoh}buoh"; fi
  if [ $msa  -gt 0 ]; then echo msa  = $msa ;name+="${msa}msa"; fi
  if [ $sa   -gt 0 ]; then echo sa   = $sa  ;name+="${sa}sa"; fi
  if [ $sam  -gt 0 ]; then echo sam  = $sam ;name+="${sam}sam"; fi
  if [ $gd   -gt 0 ]; then echo gd   = $gd  ;name+="${gd}gd"; fi
  if [ $dma  -gt 0 ]; then echo dma  = $dma ;name+="${dma}dma"; fi
  if [ $am   -gt 0 ]; then echo am   = $am  ;name+="${am}am"; fi
  if [ $aq   -gt 0 ]; then echo aq   = $aq  ;name+="${aq}aq"; fi
  if [ $p    -gt 0 ]; then echo p    = $p   ;name+="${p}p"; fi
  
  if [ "$fileXYZ" != "$name.xyz" ]
  then
    name0=$name
    num=0
    test=0
    while [ $test -eq 0 ]
    do
      if [ -e $name.log ]
      then
        num=`echo $num+1 | bc`
        name=${name0}-$num
      else
        test=1
      fi
    done
    
    
    #echo fileXYZ = $fileXYZ
    base=$(basename $fileXYZ .xyz)
    #echo BASE = $base
    for i in `ls $base.*`
    do
      #echo THIS $i
      ext=${i#*.}
      mv $base.$ext $name.$ext
    done
  fi
done

