#!/bin/bash

source ~/.JKCSusersetup.txt
scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"
toolspath="$scriptpath/../"

# Default values
SLURM_TIME="144:00:00"
SLURM_PARTITION="q24,q28,q36,q40,q48,q64"
PYTHON_ARGS=()
XYZ=0
LOG=0
PKL=0
RESTART=0
INFO=0
PAR_FLAG=0

for arg in "$@"; do
  PYTHON_ARGS+=("$arg")
done

for arg in "$@"; do
  case "$arg" in
    -h|--help|-help)
      program_PYTHON "$toolspath/SCRIPTS/DATS.py" -h
      exit 0
      ;;
    -test)
      program_PYTHON "$toolspath/SCRIPTS/DATS.py" "${PYTHON_ARGS[@]}"
      exit 0
      ;;
    -info)
      program_PYTHON "$toolspath/SCRIPTS/DATS.py" "${PYTHON_ARGS[@]}" -info
      exit 0
      ;;
    *.xyz)
      input_file="$arg"
      base_name="${input_file%.*}"
      XYZ=1
      ;;
    *.log)
      LOG=1
      ;;
    *.pkl)
      PKL=1
      ;;
    -time)
      time_arg="$arg"
      ;;
    -restart)
      RESTART=1
      ;;
    -par)
      PAR_FLAG=1
      ;;
    qtest)
      SLURM_PARTITION="qtest"
      SLURM_TIME="1:00:00"
      ;;
    *)
      if [[ "$time_arg" == "-time" ]]; then
        SLURM_TIME="$arg"
        time_arg=""
      elif [[ "$par_flag" -eq 1 ]]; then
        SLURM_PARTITION="$arg"
        par_flag=0
      fi
      ;;
  esac
done

# Submit one array job for all directories
submit_array_job() {
  local SLURM_SCRIPT=$(mktemp /tmp/slurm-script.XXXXXX)

  cat > $SLURM_SCRIPT <<EOF
#!/bin/sh
#SBATCH --job-name=JKTS
##SBATCH --output=${directories[$i]}/JKTS_%a_out
#SBATCH --time=$SLURM_TIME
#SBATCH --partition=$SLURM_PARTITION
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=2000
#SBATCH --array=1-${#directories[@]}%${#directories[@]}

DIR_INDEX=\$((\$SLURM_ARRAY_TASK_ID - 1))
DIRS=(${directories[@]})
cd \${DIRS[\$DIR_INDEX]}
source ~/.JKCSusersetup.txt
program_PYTHON "$toolspath/SCRIPTS/DATS.py" "${PYTHON_ARGS[@]}" 
EOF

  sbatch $SLURM_SCRIPT
  rm $SLURM_SCRIPT
}


submit_job() {
  local SLURM_SCRIPT=$(mktemp /tmp/slurm-script.XXXXXX)

  cat > $SLURM_SCRIPT <<EOF
#!/bin/sh
#SBATCH --job-name=JKTS
#SBATCH --output=JKTS_%j_out
#SBATCH --time=$SLURM_TIME
#SBATCH --partition=$SLURM_PARTITION
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=2000

source ~/.JKCSusersetup.txt
program_PYTHON "$toolspath/SCRIPTS/DATS.py" "${PYTHON_ARGS[@]}" 
EOF

  sbatch $SLURM_SCRIPT
  rm $SLURM_SCRIPT
}

if [[ "$XYZ" -gt 0 ]]; then
    program_PYTHON "$toolspath/SCRIPTS/DATS.py" "${PYTHON_ARGS[@]}" -init
fi

for dir in */; do
    dir_name=${dir%/}
    if [[ $dir_name =~ ^$base_name(_H[0-9]+|_C[0-9]+)$ ]] || [[ $dir_name == "reactants" ]] || [[ $dir_name == "products" ]]; then
        directories+=("$dir_name")
    fi
done

if [ ${#directories[@]} -gt 0 ] && [ "$RESTART" -lt 1 ]; then
  submit_array_job
elif [ "$PKL" -gt 0 ] || [ "$LOG" -gt 0 ]; then
  submit_job
fi
