#!/bin/bash

FROM=0.0
TO=10.0
Qfromto=0
SKIP=0
MULTIPLIER=1

scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"
toolspath="$scriptpath/../"


arguments=("$@")       # arguments of this script
arguments_help=()      # 
arguments_help_pass=() # arguments which are passed if all arguments are passed

function print_help(){
  echo "No help ... Muhaha"
  sleep 2
  echo "ok, at least some examples:"
  echo "  cd SIMULATION #multiple simcalc_LM_X_Y.pkl should be present here"
  echo "  JKumbrellaintegration"
  echo "    or"
  echo "  JKumbrellaintegration -skip 10000 -range 3.4 10.0"
  echo "  SKIP - default skipping nothing, number of steps"
  echo "  range - only for graphical visulazation"
  echo "  multiplier - default 1, either 1 or 2 for the same molecules, or just use -symm"
  echo "  THIS SHOULD PRODUCE FREE ENERGY PROFILES BUT YET NOT FREE ENERGIES" 
  exit
}

last=""
for i in "${!arguments[@]}"
do
  iter="${arguments[$i]}"
  # select
  if [ "$iter" == "-help" ]
  then
    print_help
    exit
  fi
  if [ "$iter" == "-range" ]
  then
    last="-range"
    continue
  fi
  if [ "$last" == "-range" ]
  then
    FROM=$iter
    last="-range2"
    continue
  fi
  if [ "$last" == "-range2" ]
  then
    TO=$iter
    Qfromto=1
    last=""
    continue
  fi
  if [ "$iter" == "-skip" ]
  then
    last="-skip"
    continue
  fi
  if [ "$last" == "-skip" ]
  then
    last=""
    SKIP=$iter
    continue
  fi
  if [ "$iter" == "-symm" ]
  then
    MULTIPLIER=2
    continue
  fi 
  if [ "$iter" == "-multiplier" ]
  then
    last="-multiplier"
    continue
  fi
  if [ "$last" == "-multiplier" ]
  then
    last=""
    MULTIPLIER=$iter
    continue
  fi
  echo "I do not understand this: $iter"
  exit
done

source ~/.JKCSusersetup.txt

currentdir=$PWD
if [ ! -e ~/Applications ]
then
  mkdir ~/Applications
fi
if [ ! -e ~/Applications/umbrella_integration ]
then
  cd ~/Applications
  git clone https://github.com/ATB-UQ/umbrella_integration.git
  cd $currentdir
fi

if [ ! -e umbrella_integration ]; then mkdir umbrella_integration; fi
cd umbrella_integration
if [ -e input.txt ]; then rm input.txt; fi
for i in ../simcalc-LM_*.pkl
do
  JKQC $i -column log md_time -column log COM_distance -column log harm_distance -column log k_bias -noex -filter_gt log,md_step $SKIP | awk '{print $1 " " $2 " " $3 " " $4*4.184}' | column -t >> input.txt
done
if [ $Qfromto == 0 ]; then FROM=`cat input.txt | awk '{print $3}' | sort -n | head -n 1`; fi
if [ $Qfromto == 0 ]; then TO=`cat input.txt | awk '{print $3}' | sort -n | tail -n 1`; fi
echo "Integrating from $FROM to $TO"
module load python/2.7.14
python2.7 /home/kubeckaj/Applications/umbrella_integration/umbrella_integration.py -i input.txt -t 298.15 -b 0.01 -pp pic1 -ph pic2 -o out -m $FROM $TO
if [ -e out ]; 
then
  program_PYTHON $toolspath/SCRIPTS/JKumbrella_integration.py $MULTIPLIER >> output
fi
cd ..
